# mirroring
[[registry]]
location = "docker.io"
[[registry.mirror]]
location = "docker.1ms.run"
[[registry.mirror]]
location = "docker.nastool.de"
[[registry.mirror]]
location = "hub1.nat.tf"
[[registry.mirror]]
location = "dockerpull.org"
[[registry.mirror]]
location = "docker.m.daocloud.io"
