[[registry]]
location = "registry.k8s.io/ingress-nginx/controller"
[[registry.mirror]]
location = "registry.aliyuncs.com/google_containers/nginx-ingress-controller"

[[registry]]
location = "registry.k8s.io/ingress-nginx/kube-webhook-certgen"
[[registry.mirror]]
location = "registry.aliyuncs.com/google_containers/kube-webhook-certgen"
