[[registry]]
location = "registry.k8s.io/sig-storage/nfsplugin"
[[registry.mirror]]
location = "docker.io/dyrnq/nfsplugin"

[[registry]]
location = "registry.k8s.io/sig-storage/csi-provisioner"
[[registry.mirror]]
location = "docker.io/dyrnq/csi-provisioner"

[[registry]]
location = "registry.k8s.io/sig-storage/livenessprobe"
[[registry.mirror]]
location = "docker.io/dyrnq/livenessprobe"

[[registry]]
location = "registry.k8s.io/sig-storage/csi-node-driver-registrar"
[[registry.mirror]]
location = "docker.io/dyrnq/csi-node-driver-registrar"

[[registry]]
location = "registry.k8s.io/sig-storage/csi-snapshotter"
[[registry.mirror]]
location = "docker.io/dyrnq/csi-snapshotter"

[[registry]]
location = "registry.k8s.io/sig-storage/csi-resizer"
[[registry.mirror]]
location = "docker.io/dyrnq/csi-resizer"

[[registry]]
location = "registry.k8s.io/sig-storage/csi-attacher"
[[registry.mirror]]
location = "docker.io/dyrnq/csi-attacher"
