[[registry]]
location = "registry.k8s.io/kube-apiserver"
[[registry.mirror]]
location = "registry.aliyuncs.com/google_containers/kube-apiserver"
[[registry.mirror]]
location = "docker.io/dyrnq/kube-apiserver"

[[registry]]
location = "registry.k8s.io/kube-controller-manager"
[[registry.mirror]]
location = "registry.aliyuncs.com/google_containers/kube-controller-manager"
[[registry.mirror]]
location = "docker.io/dyrnq/kube-controller-manager"

[[registry]]
location = "registry.k8s.io/kube-scheduler"
[[registry.mirror]]
location = "registry.aliyuncs.com/google_containers/kube-scheduler"
[[registry.mirror]]
location = "docker.io/dyrnq/kube-scheduler"

[[registry]]
location = "registry.k8s.io/kube-proxy"
[[registry.mirror]]
location = "registry.aliyuncs.com/google_containers/kube-proxy"
[[registry.mirror]]
location = "docker.io/dyrnq/kube-proxy"

[[registry]]
location = "registry.k8s.io/pause"
[[registry.mirror]]
location = "registry.aliyuncs.com/google_containers/pause"
[[registry.mirror]]
location = "docker.io/dyrnq/pause"

[[registry]]
location = "registry.k8s.io/etcd"
[[registry.mirror]]
location = "registry.aliyuncs.com/google_containers/etcd"
[[registry.mirror]]
location = "docker.io/dyrnq/etcd"

[[registry]]
location = "registry.k8s.io/coredns/coredns"
[[registry.mirror]]
location = "registry.aliyuncs.com/google_containers/coredns"
[[registry.mirror]]
location = "docker.io/dyrnq/coredns"

[[registry]]
location = "registry.k8s.io/metrics-server/metrics-server"
[[registry.mirror]]
location = "registry.aliyuncs.com/google_containers/metrics-server"