unqualified-search-registries = [ "docker.io", "quay.io" ]
short-name-mode = "enforcing"

# mirroring
#[[registry]]
#location = "docker.io"
#[[registry.mirror]]
#location = "docker.io.local"
#insecure = true

# mirroring
#[[registry]]
#location = "quay.io"
#[[registry.mirror]]
#location = "quay.io.local"
#insecure = true
